# Generated by Django 3.0.5 on 2020-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200418_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=9)),
                ('desc', models.CharField(default='Your order is on the way', max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='mydel',
        ),
    ]
