# Generated by Django 3.0.5 on 2020-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200418_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='query',
            field=models.CharField(default='', max_length=300),
        ),
    ]
